name: todolist
description: "A simple and practical daily task management application (to-do list), built to practice and implement core software development concepts."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
